version: '3.5'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'gunicorn lemonbase_onboarding_review_service.wsgi --bind 0.0.0.0:8000'
    volumes:
      - '.:/code'
    ports:
      - '8000:8000'
    networks:
      - proxynet

networks:
  proxynet:
    name: 'docker_network'
