# Generated by Django 3.0.8 on 2020-08-19 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_service', '0002_auto_20200810_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewcycle',
            name='reviewee',
        ),
        migrations.AddField(
            model_name='reviewcycle',
            name='reviewees',
            field=models.ManyToManyField(related_name='_reviewcycle_reviewees_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
