# Generated by Django 3.0.8 on 2020-08-23 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_service', '0003_auto_20200820_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewcycle',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='review_cycle',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='review_service.ReviewCycle'),
            preserve_default=False,
        ),
    ]
